apiVersion: v1
kind: Secret
metadata:
  name: nominatim-secret
data:
  nom_username: {{ .Values.nominatim.username | b64enc }}
  nom_password: {{ .Values.nominatim.password | b64enc }}
  nom_web_username: {{ .Values.nominatim.web.username | b64enc }}
  nom_web_password: {{ .Values.nominatim.web.password | b64enc }}