kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nominatim-postgres
  namespace: ally-dev
  labels:
    app: nominatim-postgres
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nominatim-postgres:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile-pg
  source:
    type: Git
    git:
      uri: 'https://github.com/ally-jarrett/nominatim-ocp'
  runPolicy: Serial
